version: 2.1
orbs: 
  browser-tools: circleci/browser-tools@1.3.0
jobs:
  test:
    working_directory: ~/vue-recaptcha
    docker:
      - image: cimg/node:16.16-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - restore_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}
      - run:
          name: Install depencies
          command: yarn install
      - save_cache:
          key: dependency-cache-v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - save_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test
      - store_test_results:
          path: reports
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
