name: Build document

on:
  push:
    branches:
      - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions4git/setup-git@v1
      - uses: moonrepo/setup-toolchain@v0
      - run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Build and publish document
        run: moon run docs:publish
        env:
          NODE_OPTIONS: --max-old-space-size=8192
