name: Build document

on:
  push:
    branches:
      - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Build and publish document
        run: yarn workspace @vue-recaptcha/doc generate
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - name: Check output file
        run: test -f ./docs/.output/public/200.html && test -d ./docs/.output/public/_nuxt
      - name: Create nojekyll
        run: touch ./docs/.output/public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.output/public
