name: Playwright Tests
on:
  push:
    branches: [v3, main]
  pull_request:
    branches: [v3, main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: moonrepo/setup-toolchain@v0
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: moon run vue-recaptcha:test-e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
